import type { Issue } from './types';

export const mockIssues: Issue[] = [
  {
    id: '1',
    title: 'Massive Pothole on Main St',
    description: 'A very large and dangerous pothole has formed in the middle of Main Street, near the central library. It has already caused damage to several vehicles. Urgent repair is needed.',
    category: 'Road Maintenance',
    status: 'Open',
    location: 'Main St, Johannesburg',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'pothole road',
    createdAt: '2024-07-20T10:00:00Z',
    updatedAt: '2024-07-20T10:00:00Z',
    reporter: {
      name: 'Jane Doe',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    votes: 42,
    comments: 5,
  },
  {
    id: '2',
    title: 'Streetlight out for 3 weeks',
    description: 'The streetlight on the corner of 5th and Elm has been out for several weeks, making the area very dark and unsafe at night.',
    category: 'Electricity',
    status: 'Acknowledged',
    location: '5th & Elm, Cape Town',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'streetlight night',
    createdAt: '2024-07-15T14:30:00Z',
    updatedAt: '2024-07-18T11:00:00Z',
    reporter: {
      name: 'John Smith',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    votes: 15,
    comments: 2,
  },
  {
    id: '3',
    title: 'Leaking Water Pipe',
    description: 'There is a constant stream of clean water leaking from a pipe on Bree Street. It has been going on for days and a lot of water is being wasted.',
    category: 'Water and Sanitation',
    status: 'In Progress',
    location: 'Bree Street, Durban',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'water leak',
    createdAt: '2024-07-19T08:00:00Z',
    updatedAt: '2024-07-21T09:20:00Z',
    reporter: {
      name: 'Susan Chen',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    votes: 28,
    comments: 11,
  },
  {
    id: '4',
    title: 'Waste collection missed',
    description: 'The municipal waste was not collected this week on our street. Bins are overflowing and it is becoming a health hazard.',
    category: 'Waste Management',
    status: 'Resolved',
    location: 'Protea Lane, Pretoria',
    createdAt: '2024-07-12T09:00:00Z',
    updatedAt: '2024-07-14T16:45:00Z',
    reporter: {
      name: 'David Patel',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    votes: 8,
    comments: 1,
  },
   {
    id: '5',
    title: 'Broken Traffic Signal',
    description: 'The traffic light at the intersection of Nelson Mandela Drive and Walter Sisulu Avenue is not working correctly. It is stuck on red in one direction, causing major traffic jams.',
    category: 'Public Safety',
    status: 'Open',
    location: 'Nelson Mandela Drive, Bloemfontein',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'traffic light',
    createdAt: '2024-07-21T11:00:00Z',
    updatedAt: '2024-07-21T11:00:00Z',
    reporter: {
      name: 'Thabo Mbeki',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    votes: 33,
    comments: 3,
  },
   {
    id: '6',
    title: 'Fallen tree blocking road',
    description: 'A large tree fell during the storm last night and is completely blocking access to Willow Creek road. Cars cannot pass.',
    category: 'Road Maintenance',
    status: 'Acknowledged',
    location: 'Willow Creek, Port Elizabeth',
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'fallen tree',
    createdAt: '2024-07-22T07:15:00Z',
    updatedAt: '2024-07-22T09:00:00Z',
    reporter: {
      name: 'Emily Williams',
      avatarUrl: 'https://placehold.co/40x40.png',
    },
    votes: 19,
    comments: 4,
  },
];
